{
  "comments": [
    {
      "key": {
        "uuid": "69dad736_46eb68b1",
        "filename": "libc/kernel/tools/update_all.py",
        "patchSetId": 4
      },
      "lineNbr": 63,
      "author": {
        "id": 1056365
      },
      "writtenOn": "2015-09-18T03:04:46Z",
      "side": 1,
      "message": "root would contain the path of original_dir, it shouldn\u0027t be joined a second time. otherwise we may get incorrect relative path.",
      "range": {
        "startLine": 63,
        "startChar": 40,
        "endLine": 63,
        "endChar": 92
      },
      "revId": "d14e03e4d28b289c523b109580840aa993d62df9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "89df0b23_2481f6ee",
        "filename": "libc/kernel/tools/update_all.py",
        "patchSetId": 4
      },
      "lineNbr": 70,
      "author": {
        "id": 1056365
      },
      "writtenOn": "2015-09-18T03:04:46Z",
      "side": 1,
      "message": "guess this is a debugging leftover",
      "range": {
        "startLine": 70,
        "startChar": 12,
        "endLine": 70,
        "endChar": 17
      },
      "revId": "d14e03e4d28b289c523b109580840aa993d62df9",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}